name: hive_wasm_case
description: Issue reproduction sample for WASM type issues
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  # Hive local storage, originally by Simon Leir.
  # Used as value-key pair persistence service in examples 4 and 5 (Themes Playground).
  # hive: ^2.2.3 # Original Hive package
  # This is a community fork that supports WASM-GC.
  hive_ce: ^2.8.0

  # Commonly used directories on host platform file systems, by Google (flutter.dev).
  # Used to get a working storage path for Hive on Windows. This may not be
  # needed with current versions of Hive, but I never bothered to verify.
  # It at least used to be required to get hive to work correctly on Windows.
  # https://pub.dev/packages/path_provider
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
